import Head from 'next/head'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { HomeCategories } from '@/components/HomeCategories'
import { AdvantageSection } from '@/components/AdvantageSection'

import { Box, Container, Heading, SimpleGrid, Text } from '@chakra-ui/react'
import { groupProductsByCategory } from '@/utils/groupProductsByCategory'
import { HomeProductsGrid } from '@/components/HomeProductsGrid'
import Image from 'next/image'

import bannerSeason from '/public/banner-new-season.jpg'
import bannerSale from '/public/banner-sale.jpg'
import { CenteredLabel } from '@/components/CenteredLabel'

export default function Home({products, categories, productsGroupedByCategory}) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <TopBar />
        <Box marginBottom="2rem">
          <Header />
        </Box>
      <main>
        <Container size={{
          lg:'lg',
        }}>
          <HomeCategories categories={categories}/>

          <AdvantageSection />

        </Container> 
        
        <Container
          maxW={{
            base: '100%',
            md: '1110px',
          }}
          paddingX="0"
        >
          {Object.entries(productsGroupedByCategory).map(([category, products]) => {
            return (
              <Box key={category} marginBottom="4rem">
                <Heading
                  as="h2"
                  size="md"
                  textTransform="uppercase"
                  margin={{
                    base: '0 0 1rem 1rem',
                    md: '0 0 1.5rem',
                  }}
                >
                  {category}
                </Heading>
                <HomeProductsGrid products={products} />
              </Box>
            );
          })}
        </Container>
        
        <Container size={{
          lg:'lg',
        }}>
          <SimpleGrid 
            minChildWidth='255px' 
            spacing={{
              base: '1rem',
              md: '2rem'
            }}
          >

            <Box position='relative'>
              <Image src={bannerSeason} alt=''/>
              <Box
                position='absolute'
                left='50%'
                top='50%'
                transform='translate(-50%, -50%)'
              >
                <CenteredLabel>
                  <Text fontSize='sm' color='gray.500'>New Season</Text>
                  <Text fontSize='lg' fontWeight='bold' whiteSpace='nowrap'>lookbook collection</Text>
                </CenteredLabel>
              </Box>
            </Box>
            <Box position='relative'>
              <Image src={bannerSale} alt=''/>
              <Box
                position='absolute'
                left='50%'
                top='50%'
                transform='translate(-50%, -50%)'
              >
                <Text fontSize='sm' color='gray.500'>Sale</Text>
                <Text fontSize='lg' fontWeight='bold' whiteSpace='nowrap'>
                  Get UP to <Text as='span' color='red'>50% off</Text>
                </Text>
              </Box>
            </Box>
          </SimpleGrid>
        </Container>
      </main>
    </>
  )
}

//Server side
export async function getServerSideProps(context){
  const products = await fetch("https://fakestoreapi.com/products")
    .then(res => res.json())
  const categories = await fetch("https://fakestoreapi.com/products/categories")
    .then(res => res.json())

    const productsGroupedByCategory = groupProductsByCategory(products)

  return {
    props: {
      products,
      categories,
      productsGroupedByCategory
    }
  }
}