import Head from 'next/head'

import { Header } from '@/components/Header'
import { TopBar } from '@/components/TopBar'
import { HomeCategories } from '@/components/HomeCategories'
import { AdvantageSection } from '@/components/AdvantageSection'

import { Box, Container, Flex, Grid, Heading, SimpleGrid, Text } from '@chakra-ui/react'
import { ProductCard } from '@/components/ProductCard'
import { groupProductsByCategory } from '@/utils/groupProductsByCategory'
import { HomeProductsGrid } from '@/components/HomeProductsGrid'

export default function Home({products, categories, groupProductsByCategory}) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <TopBar />
        <Box marginBottom="2rem">
          <Header />
        </Box>
      <main>
        <Container size={{
          lg:'lg',
        }}>
          <HomeCategories categories={categories}/>

          <AdvantageSection />

        </Container> 
        
        <Container maxW={{
          base: '100%',
          md: '1110px'
        }}>
          {Object.entries(groupProductsByCategory).map(([category, products])=>{
            return (
                <Box key={category} marginBottom='4rem'>
                  <Heading 
                    as='h2' 
                    size='md' 
                    textTransform='uppercase' m={{
                      base: '0 0 1rem 1rem',
                      md: '0 0 1.5rem'
                    }}
                  >
                    {category}
                  </Heading>
                  <HomeProductsGrid products={products}/>
                </Box>
              )
            })
          }
        </Container>

      </main>
    </>
  )
}

//Server side
export async function getServerSideProps(context){
  const products = await fetch("https://fakestoreapi.com/products")
    .then(res => res.json())
  const categories = await fetch("https://fakestoreapi.com/products/categories")
    .then(res => res.json())

    const productsGroupedByCategory = groupProductsByCategory(products)

  return {
    props: {
      products,
      categories,
      productsGroupedByCategory
    }
  }
}