import Head from 'next/head'
import { Heading } from '@chakra-ui/react'

export default function Home({products}) {
  return (
    <>
      <Head>
        <title>eCommerce Project</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <ol>
            {
              products.map(product=>{
                return <li key={product.id}>{product.title}</li>
              })
            }
        </ol>
      </main>
    </>
  )
}

//Server side
export async function getServerSideProps(context){
  const results = await fetch('https://fakestoreapi.com/products')
  .then(res=>res.json())
  
  return {
    props: {
      results
    }
  }
}